name: Build Jekyll Blog and Add to Blog Branch

on:
  push:
    branches:
      - main

jobs:
  jenkins-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Use GitHub Actions' cache to cache dependencies on servers
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      # Use GitHub Deploy Action to build and deploy to Github
      - uses: jeffreytse/jekyll-deploy-action@v0.3.1
        with:
          provider: 'github'
          token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
          repository: ''             # Default is current repository
          branch: 'blog'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: '>=0'         # Default is latest bundler version
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
      
      # Check out the blog branch
      - uses: actions/checkout@v3
        with:
          ref: blog 

      - name: Move files to blog directory 
        run: mkdir blog; | 
         mv [!blog]* blog/
         mv [!blog]/* blog/

      # Add the files to an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: blog-d 
          path: ./blog 
      
      #- name: Deploy
      #  uses: lbertenasco/s3-deploy@v1
      #  with:
      #      folder: blog
      #      bucket: ${{ secrets.S3_BUCKET }}
      #      dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #      invalidation: / *