name: Create artifact from blog branch and upload to s3

on:
  push:
      branches:
        - blog 

jobs:
  upload-artifact-s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Move files to blog directory 
        run: mkdir blog; | 
         mv [!blog]* blog/
         mv [!blog]/* blog/

      # Add the files to an artifact
      - uses: actions/upload-artifact@v3
        with:
          name: blog-upload
          path: ./blog 
